#!/bin/bash
# Complete Issue #168 contribution

cd ~/getting-started-guides

echo "📝 Issue #168 기여 완료"
echo "======================"
echo ""

# 변경사항 확인
echo "1️⃣ 변경사항 확인..."
git diff

echo ""
read -p "변경사항이 맞습니까? (y/n): " confirm

if [ "$confirm" != "y" ]; then
    echo "작업을 취소합니다."
    exit 1
fi

# 커밋
echo "2️⃣ 커밋 생성..."
git add .
git commit -s -m "docs: fix jarfile name in rest-service guide

The guide incorrectly stated to run the jarfile with:
java -jar target/gs-rest-service-0.1.0.jar

However, Maven actually generates:
target/rest-service-0.0.1-SNAPSHOT.jar

This change updates the documentation to use the correct filename,
preventing the 'Error: Unable to access jarfile' error.

Fixes #168"

# 푸시
echo "3️⃣ 원격 저장소에 푸시..."
git push -u origin fix/issue-168-jarfile-name

echo ""
echo "✅ 푸시 완료!"
echo ""
echo "PR 생성 URL:"
echo "https://github.com/answndud/getting-started-guides/pull/new/fix/issue-168-jarfile-name"
echo ""
echo "PR 제목: docs: fix jarfile name in rest-service guide"
echo ""
echo "PR 본문:"
cat << 'EOF'
## Description
Fixed incorrect jarfile name in the RESTful Web Service guide that was causing "Error: Unable to access jarfile" errors.

## Problem
The guide instructed users to run:
```bash
java -jar target/gs-rest-service-0.1.0.jar
```

But Maven actually generates:
```bash
target/rest-service-0.0.1-SNAPSHOT.jar
```

## Solution
Updated the documentation to use the correct filename generated by Maven.

## Testing
- [x] Verified the correct jarfile name after running `./mvnw clean package`
- [x] Tested the command locally to ensure it works

## Related Issue
Fixes #168

## Checklist
- [x] Documentation updated
- [x] No code changes
- [x] Verified locally
- [x] DCO sign-off included
EOF

echo ""
